from .First_platform import PlatformFirst
from .KSP_platform import PlatformKSP
from .SIP_High_platform import SIPHighPlatform
from .Sp_Fragile_PlatForm import SpFragilePlatform
from .Sp_Up_PlatForm import SpUpPlatform
from .SP_RightFragile_Platform import SPrightFrpPlatform
from .SP_IceFragileQ_Platform import SPICEPlatformQ
from .Sp_Down_PlatForm import  SpDownPlatform
from .SIP_RightMove_Platform import SIPrightMovePlatform
from .SP_IceFragile_PlatForm import SPICEPlatform
from .platform import Platform
from .Player_Contal_platForm import PlatformControl